### ISSUE TITLE
Bug: Template variable may generate wrong metrics

### ISSUE THREAD

**Issue by ericpai** [laincloud/hagrid#2]
Example:
metric: `$node_ex.a.b`
template: `{node => (node1, node2, node3), node_ex => (node_ex1,node_ex2,node_ex3)`
expected result: `node_ex1.a.b, node_ex2.a.b, node_ex3.a.b`
actual result: `node1_ex.a.b, node2_ex.a.b, node3_ex.a.b`

**Comment by xtao** [comment]
这是不支持变量里面有 `_`
